version: '3.7'

services:

  # rabbitmq 默认账户：guest guest （正式环境应该设置“默认”账户并设置密码，此时guest会被自动禁用）
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always

networks:
  env-net:
    external: true
  default:
    external:
     name: env-net

