version: '3.7'

services:
  mysql:
    ports:
      - '8706:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - type: bind
        source: /e/Docker/Data/Leapard/Mysql/data
        target: /var/lib/mysql
      - type: bind
        source: /e/Docker/Data/Leapard/Mysql/config/my.cnf
        target: /etc/my.cnf
  portainer:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 800M
        reservations:
          cpus: '0.1'
          memory: 256M
    ports:
      - '9000:9000'
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - type: bind
        # 配置文件
        source: /e/Docker/Data/Leapard/Portainer/
        target: /data