version: '3.7'

services:
  mysql:
    ports:
      - '8706:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - type: bind
        source: /usr/local/data/env/mysql/data
        target: /var/lib/mysql
      - type: bind
        source: /usr/local/abp-vue-vben-admin/aspnetcore/environment/other/mysql/config/my.cnf
        target: /etc/my.cnf


