version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always

  # baget:
  #   image: loicsharma/baget:latest
  #   restart: always
  #   ports:
  #     - '9002:80'
  #   environment:
  #     env-file: /usr/local/abp-vue-vben-admin/aspnetcore/environment/other/baget/config/baget.env
  #   volumes:
  #     - type: bind
  #       source: /usr/local/data/nuget/baget-data
  #       target: /var/baget
  #   container_name: baget-nuget
  #   networks:
  #     - my-net

  # 设置初始账户  admin  ZU6blm}5%K
  # 使用portainer连接远程docker
  # https://www.cnblogs.com/eastwood001/p/16086702.html
  #   2375是docker远程操控的默认端口，通过这个端口可以直接对远程的docker daemon进行操作。
  #   docker -H tcp://127.0.0.1:2375 ps
  #   http://127.0.0.1:2375/version
  # 【运维部署】windows下docker开启远程访问
  # 要配置端口映射，使用【管理员身份】cmd的ipconfig查看本机的ip再进行配置端口映射
  # https://zhuanlan.zhihu.com/p/148887874
  # netsh interface portproxy add v4tov4 listenport=2375 connectaddress=127.0.0.1 connectport=2375 listenaddress=<your-public-ip> protocol=tcp
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always

networks:
  env-net:
    external: true
  default:
    external:
     name: env-net
