version: '3.7'

services:
  nginx:
    image: nginx.img
    build:
      context: nginx/
    restart: always
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: /usr/local/data/env/nginx/logs
        target: /var/log/nginx
      - type: bind
        source: /usr/local/application/static
        target: /usr/local/application/static
      - type: bind
        source: /usr/local/data/env/nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: /usr/local/data/env/nginx/conf/conf.d/
        target: /etc/nginx/conf.d/
    container_name: nginx
    networks:
      - my-net

  mysql:
    image: mysql.img
    build:
      context: mysql/
    restart: always
    ports:
      - '8706:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - type: bind
        source: /usr/local/data/env/mysql/data
        target: /var/lib/mysql
      - type: bind
        source: /usr/local/abp-vue-vben-admin/aspnetcore/environment/other/mysql/config/my.cnf
        target: /etc/my.cnf
    container_name: mysql
    networks:
      - my-net

  # baget:
  #   image: loicsharma/baget:latest
  #   restart: always
  #   ports:
  #     - '9002:80'
  #   environment:
  #     env-file: /usr/local/abp-vue-vben-admin/aspnetcore/environment/other/baget/config/baget.env
  #   volumes:
  #     - type: bind
  #       source: /usr/local/data/nuget/baget-data
  #       target: /var/baget
  #   container_name: baget-nuget
  #   networks:
  #     - my-net
      
networks:
  my-net:
    driver: bridge
