version: '3.7'

services:
  nginx:
    image: nginx.img
    build:
      context: nginx/
    restart: always
    container_name: nginx
    external_links:
      - backend-admin-app.gateway
    networks:
      - my-net

  mysql:
    image: mysql.img
    build:
      context: mysql/
    container_name: mysql
    restart: always
    networks:
      - my-net

  # baget:
  #   image: loicsharma/baget:latest
  #   restart: always
  #   ports:
  #     - '9002:80'
  #   environment:
  #     env-file: /usr/local/abp-vue-vben-admin/aspnetcore/environment/other/baget/config/baget.env
  #   volumes:
  #     - type: bind
  #       source: /usr/local/data/nuget/baget-data
  #       target: /var/baget
  #   container_name: baget-nuget
  #   networks:
  #     - my-net

  # 初始账户  admin  a123456789
  # 使用portainer连接远程docker
  # https://www.cnblogs.com/eastwood001/p/16086702.html
  # 解决Windows安装Docker Desktop后Portainer连接不上问题
  # 要配置端口映射，使用cmd的ipconfig查看本机的ip再进行配置端口映射
  # https://blog.csdn.net/qq_38225558/article/details/117846612
  portainer:
    image: portainer.img
    build:
      context: portainer/
    container_name: portainer
    restart: always
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
  default:
    external:
     name: aspnetcore_my-net
