version: '3.7'

services:
  nginx:
    image: nginx.img
    build:
      context: nginx/
    restart: always
    container_name: nginx
    external_links:
      - backend-admin-app.gateway
    ports:
      - '80:80'
    volumes:
      - /usr/local/environment/nginx/logs:/var/log/nginx
      - /usr/local/environment/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/environment/nginx/env.js:/etc/nginx/env.js
      - /usr/local/environment/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /usr/local/environment/nginx/html/leopard:/usr/share/nginx/html/leopard
      #- /usr/local/application/certificate/:/etc/nginx/ssl/

  mysql:
    ports:
      - '8706:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - /usr/local/environment/mysql/data:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf

  portainer:
    ports:
      - '9000:9000'
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/environment/portainer/data:/data
