version: '3.7'

services:
  sso.auth-server.api:
    environment:
      - TZ=Asia/Shanghai
      # Production 、 Development
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/config/certificate/test.pfx
    volumes:
      - /usr/local/application/certificate:/app/config/certificate:rw
      - /usr/local/application/logs/sso.auth-server.api:/app/Logs:rw
      - /usr/local/application/config/sso.auth-server.api/appsettings.json:/app/appsettings.json:rw
      - /usr/local/application/config/sso.auth-server.api/appsettings.Production.json:/app/appsettings.Production.json:rw

  sso.auth-server.identityserver:
    environment:
      - TZ=Asia/Shanghai
      # Production 、 Development
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/config/certificate/test.pfx
    volumes:
      - /usr/local/application/certificate:/app/config/certificate:rw
      - /usr/local/application/logs/sso.auth-server.identityserver:/app/Logs:rw
      - /usr/local/application/config/sso.auth-server.identityserver/appsettings.json:/app/appsettings.json:rw
      - /usr/local/application/config/sso.auth-server.identityserver/appsettings.Production.json:/app/appsettings.Production.json:rw

  leopard.backend-admin.api:
    environment:
      - TZ=Asia/Shanghai
      # Production 、 Development
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/config/certificate/test.pfx
    volumes:
      - /usr/local/application/certificate:/app/config/certificate:rw
      - /usr/local/application/logs/leopard.backend-admin.api:/app/Logs:rw
      - /usr/local/application/config/leopard.backend-admin.api/appsettings.json:/app/appsettings.json:rw
      - /usr/local/application/config/leopard.backend-admin.api/appsettings.Production.json:/app/appsettings.Production.json:rw

  backend-admin-app.gateway:
    environment:
      - TZ=Asia/Shanghai
      # Production 、 Development
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/config/certificate/test.pfx
    volumes:
      - /usr/local/application/certificate:/app/config/certificate:rw
      - /usr/local/application/logs/backend-admin-app.gateway:/app/Logs:rw
      - /usr/local/application/config/backend-admin-app.gateway/appsettings.json:/app/appsettings.json:rw
      - /usr/local/application/config/backend-admin-app.gateway/appsettings.Production.json:/app/appsettings.Production.json:rw
      - /usr/local/application/config/backend-admin-app.gateway/Ocelot_Production:/app/Ocelot_Production:rw

  internal.gateway:
    environment:
      - TZ=Asia/Shanghai
      # Production 、 Development
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/config/certificate/test.pfx
    volumes:
      - /usr/local/application/certificate:/app/config/certificate:rw
      - /usr/local/application/logs/internal.gateway:/app/Logs:rw
      - /usr/local/application/config/internal.gateway/appsettings.json:/app/appsettings.json:rw
      - /usr/local/application/config/internal.gateway/appsettings.Production.json:/app/appsettings.Production.json:rw
      - /usr/local/application/config/internal.gateway/Ocelot_Production:/app/Ocelot_Production:rw

  public-web-site.gateway:
    environment:
      - TZ=Asia/Shanghai
      # Production 、 Development
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/config/certificate/test.pfx
    volumes:
      - /usr/local/application/certificate:/app/config/certificate:rw
      - /usr/local/application/logs/public-web-site.gateway:/app/Logs:rw
      - /usr/local/application/config/public-web-site.gateway/appsettings.json:/app/appsettings.json:rw
      - /usr/local/application/config/public-web-site.gateway/appsettings.Production.json:/app/appsettings.Production.json:rw
      - /usr/local/application/config/public-web-site.gateway/Ocelot_Production:/app/Ocelot_Production:rw

