version: '3.7'

services:
  sso.auth-server.api:
    image: sso.auth-server.api.img
    restart: always
    build:
      context: .
      dockerfile: ./microservices/SSO.AuthServer/SSO.AuthServer.HttpApi.Host/Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_URLS=http://+80;https://+443
    container_name: sso.auth-server.api
    ports:
      - 44102:80
      - 44105:443

  sso.auth-server.identityserver:
    image: sso.auth-server.identityserver
    restart: always
    build:
      context: .
      dockerfile: ./microservices/SSO.AuthServer/SSO.AuthServer.IdentityServer/Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_URLS=http://+80;https://+443
    container_name: sso.auth-server.identityserver
    ports:
      - 44112:80
      - 44115:443
    depends_on: 
      - sso.auth-server.api

  leopard.backend-admin.api:
    image: leopard.backend-admin.api.img
    restart: always
    build:
      context: .
      dockerfile: ./microservices/BackendAdmin/Leopard.BackendAdmin.HttpApi.Host/Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_URLS=http://+80;https://+443
    container_name: leopard.backend-admin.api
    ports:
      - 44142:80
      - 44145:443
    networks:
      - my-net

  backend-admin-app.gateway:
    image: backend-admin-app.gateway.img
    restart: always
    build:
      context: .
      dockerfile: ./gateways/BackendAdminAppGateway.Host/Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_URLS=http://+80;https://+443
    container_name: backend-admin-app.gateway
    ports:
      - 44802:80
      - 44805:443
    networks:
      - my-net

  #internal.gateway:
  #  image: internal.gateway.img
  #  restart: always
  #  build:
  #    context: .
  #    dockerfile: ./gateways/InternalGateway.Host/Dockerfile
  #  environment:
  #    - TZ=Asia/Shanghai
  #    - ASPNETCORE_URLS=http://+80;https://+443
  #  container_name: internal.gateway
  #  ports:
  #    - 44812:80
  #    - 44815:443
  #  networks:
  #    - my-net

  #public-web-site.gateway:
  #  image: public-web-site.gateway.img
  #  restart: always
  #  build:
  #    context: .
  #    dockerfile: ./gateways/PublicWebSiteGateway.Host/Dockerfile
  #  environment:
  #    - TZ=Asia/Shanghai
  #    - ASPNETCORE_URLS=http://+80;https://+443
  #  container_name: public-web-site.gateway
  #  ports:
  #    - 44822:80
  #    - 44825:443
  #  networks:
  #    - my-net

networks:
  my-net:
    driver: bridge