version: '3.7'

services:
  sso.auth-server.host:
    image: sso.auth-server.host.img
    build:
      context: .
      dockerfile: ./microservices/BackendAdmin/Leopard.BackendAdmin.HttpApi.Host/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:44105
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: sso.auth-server.host
    networks:
      - my-net

networks:
  my-net:
    driver: bridge