version: '3.2'

services:
  consul:
    image: consul.img
    build:
      context: consul/
    restart: always
    ports:
      - '8500:8500'
    container_name: consul
    networks:
      - my-net

  rabbitmq:
    image: rabbitmq.img
    build:
      context: rabbitmq/
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - type: bind
        source: /usr/local/data/env/rabbitmq
        target: /var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    container_name: rabbitmq
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
