version: '3.7'

services:
  consul:
    image: consul.img
    container_name: consul
    build:
      context: consul/
    restart: always
    ports:
      - '8500:8500'

  redis:
    ports:
      - "6379:6379"
    command: redis-server --requirepass admin123

  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - /usr/local/environment/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123

