version: '3.7'

services:
  consul:
    network_mode: "host"

  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - type: bind
        source: /e/Docker/Data/RabbitMQ_Abp_Leapard
        target: /var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123

