version: '3.7'

services:
  # local 不安装consul，直接使用exe安装consul。
  # 因为安装到docker的consul做心跳检测，没办法检测本地调试的 localhost api
  # 只能检查同样运行在docker中的 localhost api (属于不同局域网)
  # https://www.cnblogs.com/taomylife/p/9997614.html   (注意sc.exe create中创建服务时，consul拼错了)

  redis:
    ports:
      - "6379:6379"

  # http://localhost:15672/
  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - type: bind
        source: /e/Docker/Data/Leapard/RabbitMQ
        target: /var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123

