version: '3.7'

services:
  consul:
    image: consul.img
    build:
      context: consul/
    restart: always
    container_name: consul
    networks:
      - my-net

  rabbitmq:
    image: rabbitmq.img
    build:
      context: rabbitmq/
    restart: always
    container_name: rabbitmq
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
