version: '3.7'

services:
  consul:
    ports:
      - '8500:8500'
    networks:
      - my-net
      
  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - type: bind
        source: /usr/local/data/env/rabbitmq
        target: /var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123

