version: '3.2'

services:
  nginx:
    image: nginx.img
    build:
      context: nginx/
    restart: always
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: /usr/local/data/env/nginx/logs
        target: /var/log/nginx
      - type: bind
        source: /usr/local/application/static
        target: /usr/local/application/static
      - type: bind
        source: /usr/local/data/env/nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: /usr/local/data/env/nginx/conf/conf.d/
        target: /etc/nginx/conf.d/
    container_name: nginx
    networks:
      - my-net
  mysql:
    image: mysql.img
    build:
      context: mysql/
    restart: always
    ports:
      - '8706:3306'
    environment:
      - MYSQL_ROOT_PASSWORD: "37#idA2&3v"
      - MYSQL_USER: 'root'
      - MYSQL_PASS: '37#idA2&3v'
    volumes:
      - type: bind
        source: ./data
        target: /usr/local/data/env/mysql/data
      - type: bind
        source: ./conf/my.cnf
        target: /usr/local/data/env/mysql/config/my.cnf
    container_name: mysql
    networks:
      - my-net
      
networks:
  my-net:
    driver: bridge
